[package]
name = "timeout"
version = "0.1.0"
edition = "2018"
authors = ["Li Huanshuai <lihuanshuaiplus@qq.com>"]

[dependencies]
web-view = { version = "0.7.3" }

[features]
edge = ["web-view/edge"]

[dev-dependencies]
