[package]
name = "timeout"
version = "0.1.0"
edition = "2018"
authors = ["Li Huanshuai <lihuanshuaiplus@qq.com>"]

[dependencies]
web-view = { version = "0.7", features = ["edge"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
